### ISSUE TITLE
Prepare a minor release (v2.3.1)

### ISSUE THREAD

**Issue by guihkx** [nuttyartist/notes#701]
This is needed because the AppImages of release 2.3.0 are broken.

@nuttyartist Let me know if your schedule is tight and I can handle this release (I'll open a PR for review first).

---

**TODO:**

- [x] Draft a new release (#702)
- [x] Tag `v2.3.1` and push it
- [x] Make a new GitHub release
- [x] Edit release v2.3.0 to inform Linux users to use the v2.3.1 AppImages instead
- [ ] Update `UPDATES_FOSS.json`
- [x] Update [website](https://github.com/nuttyartist/notes-foss-website)'s links (https://github.com/nuttyartist/notes-foss-website/pull/2)
- [x] Update SnapStore
- [x] Update FlatHub (https://github.com/flathub/io.github.nuttyartist.notes/pull/12)

**Comment by nuttyartist** [comment]
Yes, please do!

**Comment by guihkx** [comment]
>Shouldn't we just re-upload the 2.3.0 AppImages, actually?

I really dislike changing previous releases like that. It's a really bad practice, IMHO.

We should just put a notice on the release page of 2.3.0, informing users that the AppImages are broken and that they should use 2.3.1 instead...

**Comment by nuttyartist** [comment]
Fair, we should inform users. Let's do it.

**Comment by nuttyartist** [comment]
I added a few more TODOs (:

**Comment by guihkx** [comment]
@nuttyartist I noticed that the `Notes.2.3.0.dmg` file in release [v2.3.0](https://github.com/nuttyartist/notes/releases/tag/v2.3.0), points to the Qt 5 build, instead of the Qt 6 (x86_64 + arm64) one. Is that intended?

**Comment by guihkx** [comment]
I think that was a mistake, because in [v2.2.0](https://github.com/nuttyartist/notes/releases/tag/v2.2.0), `Notes.2.2.0.dmg` is the Qt 6 build, which makes more sense, IMO.

**Comment by nuttyartist** [comment]
> @nuttyartist I noticed that the `Notes.2.3.0.dmg` file in release [v2.3.0](https://github.com/nuttyartist/notes/releases/tag/v2.3.0), points to the Qt 5 build, instead of the Qt 6 (x86_64 + arm64) one. Is that intended?

Nope, it is a mistake! Good catch.

**Comment by guihkx** [comment]
Well done, I completely forgot about it...
